services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: viact
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin_pass
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - viact-network
  backend:
    image: viact-backend
    build:
      context: ./
      dockerfile: dockerfile
    container_name: backend
    restart: always
    environment:
      - DB_HOST=mysql
      - ENV=prod
      - SALT_ROUNDS=10
    ports:
      - 3000:3000
    networks:
      - viact-network
    depends_on:
      - mysql
networks:
  viact-network:
    driver: bridge